// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by Hive Generator

part of 'clip_item.dart';

// **************************************************************************
// TypeAdapterGenerator
// **************************************************************************

/// ClipItemAdapter - محول Hive لنموذج ClipItem
/// Hive TypeAdapter for ClipItem model
class ClipItemAdapter extends TypeAdapter<ClipItem> {
  @override
  final int typeId = 0;

  @override
  ClipItem read(BinaryReader reader) {
    final numOfFields = reader.readByte();
    final fields = <int, dynamic>{
      for (int i = 0; i < numOfFields; i++) reader.readByte(): reader.read(),
    };
    return ClipItem(
      id: fields[0] as String,
      content: fields[1] as String,
      type: fields[2] as String,
      createdAt: fields[3] as DateTime,
      lastUsedAt: fields[4] as DateTime?,
      isPinned: fields[5] as bool? ?? false,
      isSecure: fields[6] as bool? ?? false,
      usageCount: fields[7] as int? ?? 0,
      label: fields[8] as String?,
      sourceApp: fields[9] as String?,
      subType: fields[10] as String?,
      isDeleted: fields[11] as bool? ?? false,
      encryptedContent: fields[12] as String?,
    );
  }

  @override
  void write(BinaryWriter writer, ClipItem obj) {
    writer
      ..writeByte(13)
      ..writeByte(0)
      ..write(obj.id)
      ..writeByte(1)
      ..write(obj.content)
      ..writeByte(2)
      ..write(obj.type)
      ..writeByte(3)
      ..write(obj.createdAt)
      ..writeByte(4)
      ..write(obj.lastUsedAt)
      ..writeByte(5)
      ..write(obj.isPinned)
      ..writeByte(6)
      ..write(obj.isSecure)
      ..writeByte(7)
      ..write(obj.usageCount)
      ..writeByte(8)
      ..write(obj.label)
      ..writeByte(9)
      ..write(obj.sourceApp)
      ..writeByte(10)
      ..write(obj.subType)
      ..writeByte(11)
      ..write(obj.isDeleted)
      ..writeByte(12)
      ..write(obj.encryptedContent);
  }

  @override
  int get hashCode => typeId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ClipItemAdapter &&
          runtimeType == other.runtimeType &&
          typeId == other.typeId;
}
